// Consolidate a set of Markdown files into ONE brand-plain PDF (or run once per
// group to get 2 files — see the guardrail in ../SKILL.md: gog must never send
// raw .md attachments, always these consolidated PDFs instead).
//
// Usage:
//   node md-to-pdf.mjs --title "AGSHub — Design Specs" --out ./specs.pdf file1.md file2.md ...
//   node md-to-pdf.mjs --title "..." --out ./out.pdf --glob "docs/**/*.md"
//
// Each input file becomes one section (filename as H1, its content below,
// page break before the next). Uses Playwright's bundled Chromium for
// print-to-pdf — same technique as
// ~/.claude/skills/product-demo-package/scripts/make-pdfs.mjs, kept
// deliberately simpler (no cover-page branding, this is an internal doc
// bundle, not a stakeholder deliverable).
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { marked } from 'marked';
import { chromium } from 'playwright';
import { globSync } from 'node:fs';

const args = process.argv.slice(2);
function flag(name, fallback) {
  const i = args.indexOf(`--${name}`);
  return i === -1 ? fallback : args[i + 1];
}

const title = flag('title', 'Consolidated Documentation');
const out = flag('out');
const globPattern = flag('glob');
if (!out) { console.error('--out <path.pdf> is required'); process.exit(1); }

let files = args.filter(a => !a.startsWith('--') && a !== title && a !== out && a !== globPattern);
// Drop the values consumed by --title/--out/--glob from the positional list.
const consumed = new Set([title, out, globPattern].filter(Boolean));
files = files.filter(f => !consumed.has(f));
if (globPattern) {
  files = files.concat(globSync(globPattern));
}
if (files.length === 0) { console.error('No input .md files given (positional args or --glob).'); process.exit(1); }

marked.setOptions({ gfm: true, breaks: false });

const css = `
  * { box-sizing: border-box; }
  html { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body { font-family: 'Segoe UI', ui-sans-serif, system-ui, -apple-system, sans-serif; color: #1f2937; font-size: 10pt; line-height: 1.55; margin: 0; }
  section { padding: 4px 2px; }
  section + section { page-break-before: always; }
  h1.doc-title { color: #0A1628; font-size: 20pt; margin: 0 0 4px; border-bottom: 3px solid #0A1628; padding-bottom: 8px; }
  .doc-meta { color: #6b7280; font-size: 8.5pt; margin: 0 0 16px; }
  h1 { color: #0A1628; font-size: 16pt; margin: 0 0 8px; }
  h2 { color: #0A1628; font-size: 13pt; margin: 18px 0 6px; padding-bottom: 4px; border-bottom: 1.5px solid #0A1628; page-break-after: avoid; }
  h3 { color: #243550; font-size: 11pt; margin: 14px 0 5px; page-break-after: avoid; }
  p, li { orphans: 2; widows: 2; }
  ul, ol { padding-left: 18px; margin: 6px 0; }
  li { margin: 2px 0; }
  strong { color: #0A1628; }
  a { color: #2563eb; text-decoration: none; }
  code { font-family: ui-monospace, Consolas, monospace; font-size: 8.6pt; background: #f3f4f6; padding: 1px 4px; border-radius: 3px; }
  pre { background: #0A1628; color: #e2e8f0; padding: 10px 12px; border-radius: 6px; overflow-x: auto; font-size: 8.2pt; line-height: 1.4; page-break-inside: avoid; }
  pre code { background: none; color: inherit; padding: 0; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 8.5pt; page-break-inside: avoid; }
  th { background: #0A1628; color: #fff; text-align: left; padding: 6px 8px; }
  td { border: 1px solid #e5e7eb; padding: 5px 8px; vertical-align: top; }
  tbody tr:nth-child(even) { background: #f8fafc; }
  blockquote { margin: 8px 0; padding: 6px 12px; border-left: 3px solid #2563eb; background: #f0f6ff; }
  hr { border: none; border-top: 1px solid #e5e7eb; margin: 14px 0; }
  .toc { font-size: 9pt; }
  .toc li { margin: 3px 0; }
`;

const sections = files.map((f, i) => {
  const raw = readFileSync(f, 'utf8');
  const body = marked.parse(raw);
  const name = path.basename(f);
  const heading = i === 0
    ? `<h1 class="doc-title">${title}</h1><p class="doc-meta">Consolidated from ${files.length} document${files.length === 1 ? '' : 's'} · generated by gog skill's md-to-pdf</p>`
    : '';
  return `<section>${heading}<h1>${name}</h1>${body}</section>`;
});

const html = `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>${css}</style></head>
  <body>${sections.join('\n')}</body></html>`;

const tmpDir = mkdtempSync(path.join(tmpdir(), 'md-to-pdf-'));
const htmlPath = path.join(tmpDir, 'combined.html');
writeFileSync(htmlPath, html);

const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto('file://' + htmlPath.replace(/\\/g, '/'), { waitUntil: 'networkidle' });
await page.pdf({
  path: out, format: 'A4', printBackground: true,
  margin: { top: '16mm', bottom: '16mm', left: '15mm', right: '15mm' },
  displayHeaderFooter: true,
  headerTemplate: '<span></span>',
  footerTemplate: `<div style="width:100%;font-size:8px;color:#9ca3af;padding:0 14mm;display:flex;justify-content:space-between;">
    <span>${title}</span><span>Page <span class="pageNumber"></span> / <span class="totalPages"></span></span></div>`,
});
await browser.close();

console.log(JSON.stringify({ out, files: files.length, title }));
