/**
 * The single artefact the pipeline reads. Generated by the intake, hand-editable
 * afterwards.
 *
 * Every selector below was produced by `discover-targets.mjs` against this app
 * at this viewport — none was typed from memory. That is the whole point: a
 * target can no longer be a coordinate that corresponds to nothing.
 */
export default {
  preset: 'cinematic-dark',

  brand: {
    accent: '#A78BFA',
    // Degrees the key light rotates per scene. Reference product films shift
    // cool→warm between sections; the v1-v3 builds held one hue for their whole
    // runtime, which is why they read as handsome but monotonous.
    hueDrift: 14,
  },

  motion: {
    intensity: 'cinematic',
    // Alternating stage brightness, scene to scene. Sampling a reference film's
    // luminance every 3s over its first 24s showed a ~40x swing; these builds
    // were uniformly lit throughout.
    rhythm: 'alternating',
    rhythmRange: [0.82, 1.3],
  },

  output: { genre: 'both', width: 1920, height: 1080, fps: 30, sizzleSec: 14 },

  // Reference-grade product films do not brand their own screen recording
  // continuously. Cards only, by default.
  watermark: { text: 'BOB-AGS · Product Walkthrough', mode: 'cards-only' },

  capture: {
    viewport: { width: 1600, height: 900 },
    // The marker is measured, then cut. It exists so the drawn cursor and the
    // UI's own hover state cannot drift apart.
    // searchSec must cover page load + settle, since the marker is flashed once
    // the page has painted rather than at page creation.
    calibration: { color: '#FF00FF', frames: 2, searchSec: 14 },
  },

  scenes: [
    {
      id: '01-dashboard',
      url: '/dashboard',
      settle: 'networkidle',
      caption: 'Tenant-scoped dashboard',
      sub: 'Every query filtered by account_id',
      targets: [
        { sel: 'body > div:nth-of-type(2) > main > div > div > div > div:nth-of-type(2) > div:nth-of-type(1)', dwell: 900, label: 'Total calls tile' },
        { sel: 'body > div:nth-of-type(2) > main > div > div > div > div:nth-of-type(3) > div:nth-of-type(2) > h3', dwell: 800, label: 'QA performance' },
      ],
    },
    {
      id: '02-calls',
      url: '/calls',
      settle: 'networkidle',
      caption: 'Call review & QA scoring',
      sub: 'CTM records merged with local uploads',
      targets: [
        { sel: '#direction', dwell: 700, label: 'Direction filter' },
        { sel: 'body > div:nth-of-type(2) > main > div > div > div > div:nth-of-type(5) > div > div:nth-of-type(3) > table > tbody > tr:nth-of-type(1)', dwell: 800, label: 'First call row' },
        // Expands a filter panel. Visible reaction, no mutation — the bar a
        // target must clear to opt into `click`.
        { sel: 'body > div:nth-of-type(2) > main > div > div > div > div:nth-of-type(3) > form > div:nth-of-type(3) > div > button:nth-of-type(2)', dwell: 900, click: true, label: 'More filters' },
      ],
    },
    {
      id: '03-chat-qa',
      url: '/chat-qa',
      settle: 'networkidle',
      caption: 'Chat QA, attributed',
      sub: '4,975 conversations recovered their operator',
      targets: [
        { sel: '#status', dwell: 700, label: 'Status filter' },
        { sel: 'body > div:nth-of-type(2) > main > div > div > div:nth-of-type(7) > table > tbody > tr:nth-of-type(1)', dwell: 800, label: 'First conversation' },
        { sel: 'body > div:nth-of-type(2) > main > div > div > div:nth-of-type(7) > table > tbody > tr:nth-of-type(3)', dwell: 700, label: 'Third conversation' },
        // Deliberately hover-only: "Sync Now" and "Analyze" both mutate.
      ],
    },
    {
      id: '04-supervisor',
      url: '/supervisor',
      // A page holding an open SSE stream NEVER reaches networkidle — it would
      // hang until timeout and record one motionless screen.
      settle: 'domcontentloaded',
      caption: 'Live supervisor view',
      sub: 'SSE stream, one payload per real change',
      targets: [
        { sel: 'body > div:nth-of-type(2) > main > div > div > div:nth-of-type(1) > button:nth-of-type(2)', dwell: 950, click: true, label: 'Practice tab' },
        { sel: 'body > div:nth-of-type(2) > main > div > div > div:nth-of-type(1) > button:nth-of-type(1)', dwell: 900, click: true, label: 'Live calls tab' },
      ],
    },
  ],

  intro: { kicker: 'Product Walkthrough', words: ['Meet', 'BOB-AGS.'], sub: 'Tenant-isolated call & chat quality analysis' },
  outro: { kicker: 'Sample Output', words: ['Built', 'to', 'be', 'seen.'], sub: 'One motion system across video and documents.' },
};
